name: Publicando a imagem Docker

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Enviando ao Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # https://github.com/docker/metadata-action
        uses: docker/metadata-action@v3
        with:
          images: camileite/dockercnw

      - name: Logando ao DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construindo e encaminhando
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}